### ISSUE TITLE
.rat generation tweak: select existing .rat files to further downsample them

### ISSUE THREAD

**Issue by AidanMerryman** [sashaouellet/SDMTools#5]
Would be nice to have a checkbox in the image filter of the .rat generator that says "include existing .rat files" so I can further downsample the ones I generated a while ago, I chose 1k and I'd like to choose 512 now. 

Right now I have to go re-link up all the old .exr's so I can convert them to .rat's again so I can pick 512 this time.

**Comment by sashaouellet** [comment]
Resolved in latest commit. RAT extension included as a valid image type.
